"""Initial schema setup

Revision ID: 65d07c359cdb
Revises: 
Create Date: 2026-09-02 23:19:31.892562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d07c359cdb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('nomination_required', sa.Boolean(), nullable=False),
    sa.Column('schedule_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_table('officers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('education', sa.String(), nullable=False),
    sa.Column('past_training', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_officers_id'), 'officers', ['id'], unique=False)
    op.create_table('competency_gaps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competency_gaps_id'), 'competency_gaps', ['id'], unique=False)
    op.create_index(op.f('ix_competency_gaps_officer_id'), 'competency_gaps', ['officer_id'], unique=False)
    op.create_table('competency_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('domain_scores', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competency_profiles_id'), 'competency_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_competency_profiles_officer_id'), 'competency_profiles', ['officer_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('difficulty_trace', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_id'), 'quiz_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_officer_id'), 'quiz_attempts', ['officer_id'], unique=False)
    op.create_table('nudges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('gap_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gap_id'], ['competency_gaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nudges_course_id'), 'nudges', ['course_id'], unique=False)
    op.create_index(op.f('ix_nudges_gap_id'), 'nudges', ['gap_id'], unique=False)
    op.create_index(op.f('ix_nudges_id'), 'nudges', ['id'], unique=False)
    op.create_index(op.f('ix_nudges_officer_id'), 'nudges', ['officer_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_material_id', sa.String(), nullable=True),
    sa.Column('bloom_level', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('gap_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gap_id'], ['competency_gaps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_questions_id'), 'quiz_questions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_questions_id'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_nudges_officer_id'), table_name='nudges')
    op.drop_index(op.f('ix_nudges_id'), table_name='nudges')
    op.drop_index(op.f('ix_nudges_gap_id'), table_name='nudges')
    op.drop_index(op.f('ix_nudges_course_id'), table_name='nudges')
    op.drop_table('nudges')
    op.drop_index(op.f('ix_quiz_attempts_officer_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_competency_profiles_officer_id'), table_name='competency_profiles')
    op.drop_index(op.f('ix_competency_profiles_id'), table_name='competency_profiles')
    op.drop_table('competency_profiles')
    op.drop_index(op.f('ix_competency_gaps_officer_id'), table_name='competency_gaps')
    op.drop_index(op.f('ix_competency_gaps_id'), table_name='competency_gaps')
    op.drop_table('competency_gaps')
    op.drop_index(op.f('ix_officers_id'), table_name='officers')
    op.drop_table('officers')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
